### REST Client

GET https://t6ilktug3a.execute-api.us-east-1.amazonaws.com/prod/spfinder

### Get by id

GET https://t6ilktug3a.execute-api.us-east-1.amazonaws.com/prod/spfinder?id=2e6bb13b-be8c-43c5-ba53-c91a57ba2c54

###
POST https://t6ilktug3a.execute-api.us-east-1.amazonaws.com/prod/spfinder
Content-Type: application/json

{
  "location": "Vietnam"
}
###
DELETE https://t6ilktug3a.execute-api.us-east-1.amazonaws.com/prod/spfinder

###
PUT https://t6ilktug3a.execute-api.us-east-1.amazonaws.com/prod/spfinder?id=b9346dc7-abb1-40c4-83c8-c074297b2ab5
Content-Type: application/json

{
  "location": "Eastern Laos"
}
