### REST Client

GET https://t6ilktug3a.execute-api.us-east-1.amazonaws.com/prod/spfinder

###
POST https://t6ilktug3a.execute-api.us-east-1.amazonaws.com/prod/spfinder
Content-Type: application/json

{
  "location": "Vietnam"
}
###
DELETE https://t6ilktug3a.execute-api.us-east-1.amazonaws.com/prod/spfinder

###