### REST Client

GET https://uxgyjfvr88.execute-api.us-east-1.amazonaws.com/prod/spfinder

###
POST https://uxgyjfvr88.execute-api.us-east-1.amazonaws.com/prod/spfinder

###
DELETE https://uxgyjfvr88.execute-api.us-east-1.amazonaws.com/prod/spfinder

###